apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: app-of-apps  
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:  
  project: common-resources             
  source:  
    repoURL: https://github.com/mariiasharkovskaya/infra-azure-workshop.git
    targetRevision: HEAD  
    path: argo-cd-apps/apps
  destination:  
    server: https://kubernetes.default.svc
    namespace: argocd  
  syncPolicy:  
    automated:  
      prune: true  
      selfHeal: true
      allowEmpty: true