apiVersion: argoproj.io/v1alpha1  
kind: AppProject  
metadata:  
  name: devbcn-demo-ms  
  namespace: mariia-shark-argocd  
spec:  
  description: "Project for devbcn deployments"  
  sourceRepos:  
    - "*" # Allow all repositories, or specify your Git repos explicitly  
  destinations:  
    - namespace: mariia-shark-argocd   # Allow all namespaces, or restrict to specific namespaces if needed  'https://your.git.repo/applications.git'
      server: "*"    # Allow all clusters, or restrict to specific clusters  
  clusterResourceWhitelist:  
    - group: "*"  
      kind: "*"  
  namespaceResourceWhitelist:  
    - group: "*"  
      kind: "*"  