apiVersion: argoproj.io/v1alpha1  
kind: AppProject  
metadata:  
  name: common-resources 
  namespace: argocd
spec:  
  description: "Project for common deployments"  
  sourceRepos:  
    - "*" # Allow all repositories, or specify your Git repos explicitly  
  destinations:  
    - namespace: "*"
      server: "*"    # Allow all clusters, or restrict to specific clusters  
  clusterResourceWhitelist:  
    - group: "*"  
      kind: "*"  
  namespaceResourceWhitelist:  
    - group: "*"  
      kind: "*"  