apiVersion: argoproj.io/v1alpha1  
kind: AppProject  
metadata:  
  name: devbcn-demo
  namespace: devbcn-demo  
spec:  
  description: "Project for devbcn deployments"  
  sourceRepos:  
    - "*" # Allow all repositories, or specify your Git repos explicitly  
  destinations:  
    - namespace: devbcn-demo  
      server: https://kubernetes.default.svc 
  clusterResourceWhitelist:  
    - group: "*"  
      kind: "*"  
  namespaceResourceWhitelist:  
    - group: "*"  
      kind: "*"  