apiVersion: argoproj.io/v1alpha1  
kind: AppProject  
metadata:  
  name: common-resources 
  namespace: argocd
spec:  
  description: "Project for common deployments"  
  sourceRepos:  
    - "*" 
  destinations:  
    - namespace: default
      server: "*"   
  clusterResourceWhitelist: 
    - group: "*"  
      kind: "*"  
  namespaceResourceWhitelist:  
    - group: "*"  
      kind: "*"  