apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: common-resources  
  namespace: argocd  
  annotations:  
    argocd.argoproj.io/sync-wave: "0" 
spec:  
  project: common-resources  
  source:  
    repoURL: https://github.com/mariiasharkovskaya/AzureWorkshop.git
    targetRevision: HEAD  
    path: infrastructure-repo/apps/common/base               # path to app manifest  
  destination:  
    server: https://kubernetes.default.svc  
    namespace: default              
  syncPolicy:  
    automated:  
      prune: false                   
      selfHeal: true  